src/itest/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerITest.java, src/main/java/uk/gov/companieshouse/company/profile/api/InsolvencyApiService.java, src/main/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileController.java, src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java, src/main/resources/application.yml, src/test/java/uk/gov/companieshouse/company/profile/api/InsolvencyApiClientServiceTest.java, src/test/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerTest.java, src/test/java/uk/gov/companieshouse/company/profile/service/CompanyProfileServiceTest.java
Adding context id to header for patch requests
=> DSND-377: Adding context id to header for patch requests

src/itest/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerITest.java, src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java, src/main/resources/application.yml, src/test/java/uk/gov/companieshouse/company/profile/service/CompanyProfileServiceTest.java
Creates new company profile if one doesn't exist
=> All working now

src/main/java/uk/gov/companieshouse/company/profile/api/InsolvencyApiService.java, src/main/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileController.java, src/main/java/uk/gov/companieshouse/company/profile/converter/CompanyProfileConverter.java, src/main/java/uk/gov/companieshouse/company/profile/converter/JsonDateTimeConverter.java, src/main/java/uk/gov/companieshouse/company/profile/exception/BadRequestException.java, src/main/java/uk/gov/companieshouse/company/profile/exception/ControllerExceptionHandler.java, src/main/java/uk/gov/companieshouse/company/profile/exception/ServiceUnavailableException.java, src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java, src/test/java/uk/gov/companieshouse/company/profile/api/InsolvencyApiClientServiceTest.java, src/test/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerTest.java, src/test/java/uk/gov/companieshouse/company/profile/converter/CompanyProfileConverterTest.java, src/test/java/uk/gov/companieshouse/company/profile/service/CompanyProfileServiceTest.java
- Return non-2XX response codes when issues/errors occur when calling the GET and PATCH endpoints
- Improved logging
Resolves:
https://companieshouse.atlassian.net/browse/DSND-548
=> DSND-548: Add non 2xx response codes

src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java
DSND-668 Addressing issues with updated element not present in the document. Thie element should be there in production data.
=> DSND-668 Addressing issues with updated element not presen

src/itest/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerITest.java, src/itest/java/uk/gov/companieshouse/company/profile/repository/RepositoryITest.java, src/itest/java/uk/gov/companieshouse/company/profile/steps/CompanyProfileSteps.java, src/main/java/uk/gov/companieshouse/company/profile/exception/ControllerExceptionHandler.java, src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java, src/test/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerTest.java, src/test/java/uk/gov/companieshouse/company/profile/service/CompanyProfileServiceTest.java
DSND-668 Setting UTC for the LocalDateTime
=> DSND-668 Setting UTC for the LocalDateTime

src/itest/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerITest.java, src/itest/java/uk/gov/companieshouse/company/profile/repository/RepositoryITest.java, src/itest/java/uk/gov/companieshouse/company/profile/steps/CompanyProfileSteps.java, src/main/java/uk/gov/companieshouse/company/profile/exception/ControllerExceptionHandler.java, src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java, src/test/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerTest.java, src/test/java/uk/gov/companieshouse/company/profile/service/CompanyProfileServiceTest.java
Addressing issue with updated at UTC. Mongo DB stores automatically dates in UTC.
=> DSND-839: Addressing issue with updated at UTC.

src/itest/java/uk/gov/companieshouse/company/profile/CucumberFeaturesRunnerITest.java, src/itest/java/uk/gov/companieshouse/company/profile/configuration/AbstractIntegrationTest.java, src/itest/java/uk/gov/companieshouse/company/profile/configuration/CucumberSpringConfiguration.java, src/itest/java/uk/gov/companieshouse/company/profile/repository/RepositoryITest.java, src/itest/java/uk/gov/companieshouse/company/profile/steps/CompanyProfileSteps.java, src/itest/resources/features/company-profile-error-retry.feature, src/itest/resources/features/company-profile.feature, src/itest/resources/json/input/11748564.json, src/itest/resources/json/input/bad_request_payload.json, src/itest/resources/json/input/internal_server_error.json, src/main/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileController.java, src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java, src/test/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerTest.java
DSND-734: Company Profile API Happy Path Patch endpoint
DSND-734: Company Profile API Error/Retry Integration Test Scenarios
https://companieshouse.atlassian.net/browse/DSND-734
=> DSND-734: Company Profile API Happy Path Patch endpoint

src/main/java/uk/gov/companieshouse/company/profile/serialization/LocalDateDeSerializer.java
DSND-849 Addressing issue with old dates
=> DSND-849 Addressing issue with old dates

src/main/java/uk/gov/companieshouse/company/profile/model/CompanyProfileDocument.java
=> DSND-841-hasMortgageFieldNotSetAsFalse

src/main/resources/application.yml
Resolves: https://companieshouse.atlassian.net/browse/DSND-878
=> DSND-878-Not returning nulls

pom.xml, src/main/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileController.java, src/main/java/uk/gov/companieshouse/company/profile/exception/ControllerExceptionHandler.java
Adding JSON Payload Validation fot Request Body in PATCH method and new method in ControllerExceptionHandler
=> Adding JSON Payload Validation fot Request Body in PATCH method

src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java
DSND-1042 Addressing issue when company profile was not updated as CHS Kafka API answer with 201
=> DSND-1042 Addressing issue when company profile

src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java, src/test/java/uk/gov/companieshouse/company/profile/service/CompanyProfileServiceTest.java
Resolves: https://companieshouse.atlassian.net/browse/DSND-978
Confirmed to be working locally, only updates fields:
Ignores other fields and doesn't update them, as its using mongoTemplate update query to update the specific fields in the ticket.
=> DSND-978-ChangedPatchToUseMongoTemplate

src/itest/java/uk/gov/companieshouse/company/profile/configuration/AbstractIntegrationTest.java, src/itest/java/uk/gov/companieshouse/company/profile/steps/CompanyProfileSteps.java, src/main/java/uk/gov/companieshouse/company/profile/api/CompanyProfileApiService.java, src/main/java/uk/gov/companieshouse/company/profile/config/ApplicationConfig.java, src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java, src/test/java/uk/gov/companieshouse/company/profile/api/CompanyProfileApiClientServiceTest.java, src/test/java/uk/gov/companieshouse/company/profile/service/CompanyProfileServiceTest.java
=> Sonar Qube improvements

Tiltfile.dev
=> Add tiltfile dev

pom.xml, src/itest/java/uk/gov/companieshouse/company/profile/configuration/AbstractIntegrationTest.java, src/itest/java/uk/gov/companieshouse/company/profile/configuration/WiremockTestConfig.java, src/itest/java/uk/gov/companieshouse/company/profile/steps/CompanyProfileSteps.java, src/itest/resources/application-test.yml, src/itest/resources/features/company-profile-error-retry.feature, src/main/java/uk/gov/companieshouse/company/profile/api/ApiClientServiceImpl.java, src/main/java/uk/gov/companieshouse/company/profile/api/CompanyProfileApiService.java
- stub calls to `chs-kafka-api` using `Wiremock` for the relevant scenarios
- fix wrong internal api client used
- address remaining sonar issues
=> DSND-1122 - Int test: stub calls to chs-kafka-api using Wiremock

src/itest/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerITest.java, src/itest/resources/features/company-profile-error-retry.feature, src/main/java/uk/gov/companieshouse/company/profile/config/ExceptionHandlerConfig.java, src/main/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileController.java, src/main/java/uk/gov/companieshouse/company/profile/exceptions/DocumentGoneException.java, src/main/java/uk/gov/companieshouse/company/profile/exceptions/DocumentNotFoundException.java, src/main/java/uk/gov/companieshouse/company/profile/exceptions/DocumentNotFoundExtension.java, src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java, src/test/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerTest.java, src/test/java/uk/gov/companieshouse/company/profile/exceptions/ControllerExceptionHandlerTest.java, src/test/java/uk/gov/companieshouse/company/profile/service/CompanyProfileServiceTest.java
BI-11638 - Insolvency - return a 404 response when a resource is not found
=> change resource gone messages to not found

src/itest/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerITest.java, src/main/java/uk/gov/companieshouse/company/profile/config/ExceptionHandlerConfig.java, src/main/java/uk/gov/companieshouse/company/profile/exceptions/DocumentGoneException.java, src/test/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerTest.java, src/test/java/uk/gov/companieshouse/company/profile/exceptions/ControllerExceptionHandlerTest.java
BI-11639 - Revert PATCH request from not found to gone
=> Revert PATCH request from not found to gone

src/itest/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerITest.java, src/itest/resources/features/company-profile-error-retry.feature, src/main/java/uk/gov/companieshouse/company/profile/config/ExceptionHandlerConfig.java, src/main/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileController.java, src/main/java/uk/gov/companieshouse/company/profile/exceptions/DocumentNotFoundException.java, src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java, src/test/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerTest.java, src/test/java/uk/gov/companieshouse/company/profile/exceptions/ControllerExceptionHandlerTest.java, src/test/java/uk/gov/companieshouse/company/profile/service/CompanyProfileServiceTest.java
Revert all not found status to gone
=> All not found status reverted to gone

src/itest/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerITest.java, src/itest/resources/features/company-profile-error-retry.feature, src/main/java/uk/gov/companieshouse/company/profile/config/ExceptionHandlerConfig.java, src/main/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileController.java, src/main/java/uk/gov/companieshouse/company/profile/exceptions/DocumentGoneException.java, src/main/java/uk/gov/companieshouse/company/profile/exceptions/DocumentNotFoundException.java, src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java, src/test/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerTest.java, src/test/java/uk/gov/companieshouse/company/profile/exceptions/ControllerExceptionHandlerTest.java, src/test/java/uk/gov/companieshouse/company/profile/service/CompanyProfileServiceTest.java
Company profile - return a 404 response when a resource is not found
=> Changed all status codes 410 to 404

routes.yaml
* Add routes for exemptions link PATCH endpoints
=> DSND-1406 - Add routes for exemptions link PATCH endpoints

routes.yaml
Reverts companieshouse/company-profile-api#82
Changes were not needed.
=> Revert "DSND-1406 - Add routes for exemptions link PATCH endpoints"

src/main/java/uk/gov/companieshouse/company/profile/config/ExceptionHandlerConfig.java
*  Remove unnecessary logging from when receiving HTTP 409 response.
[DSND-1460](https://companieshouse.atlassian.net/browse/DSND-1460)
[DSND-1460]: https://companieshouse.atlassian.net/browse/DSND-1460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-1460 Remove unnecessary logging from HTTP 409 response

src/itest/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerITest.java, src/itest/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileE2EITest.java, src/itest/java/uk/gov/companieshouse/company/profile/steps/CompanyProfileSteps.java, src/main/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileController.java, src/main/java/uk/gov/companieshouse/company/profile/util/LinkRequest.java, src/main/java/uk/gov/companieshouse/company/profile/util/LinkRequestFactory.java, src/test/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerTest.java, src/test/java/uk/gov/companieshouse/company/profile/service/CompanyProfileServiceTest.java
This PR implements adding a filing history link to a company profile document.
[DSND-2267](https://companieshouse.atlassian.net/browse/DSND-2267)
[DSND-2267]: https://companieshouse.atlassian.net/browse/DSND-2267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2267: Add filing history link (happy path)

routes.yaml
Reverts companieshouse/company-profile-api#141
=> Revert "temporarily remove routes"

routes.yaml, src/main/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileController.java
* Change logging messages for patch endpoint
Resolves https://companieshouse.atlassian.net/browse/DSND-2381
=> DSND-2381 Remove routes for tbirds build

routes.yaml, src/main/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileController.java
* Change logging message slightly to hopefully get a new build sorted
Resolves [DSND-2381](https://companieshouse.atlassian.net/browse/DSND-2381)
[DSND-2381]: https://companieshouse.atlassian.net/browse/DSND-2381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2381 Add back in the GET endpoints

src/main/java/uk/gov/companieshouse/company/profile/api/CompanyProfileApiService.java, src/test/java/uk/gov/companieshouse/company/profile/api/CompanyProfileApiClientServiceTest.java
- Added DELETE event type to mapChangedResource
- Added unit tests to CP API service for the delete method
=> add delete event type and unit tests

src/main/resources/application.yml
- Set mongodb.transactional to true
=> set transactional to true

src/main/java/uk/gov/companieshouse/company/profile/transform/CompanyProfileTransformer.java, src/test/java/uk/gov/companieshouse/company/profile/transform/CompanyProfileTransformerTest.java, src/test/java/uk/gov/companieshouse/company/profile/util/TestHelper.java
* Set the parent company number on Mongo document root level
* Update unit tests to test above functionality
Resolves [DSND-2551](https://companieshouse.atlassian.net/browse/DSND-2551)
[DSND-2551]: https://companieshouse.atlassian.net/browse/DSND-2551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2551: Change logic within CompanyProfileTransformer

src/itest/java/uk/gov/companieshouse/company/profile/steps/CompanyProfileSteps.java, src/itest/java/uk/gov/companieshouse/company/profile/steps/UkEstablishmentLinkSteps.java, src/itest/resources/features/add-uk-establishments-link.feature, src/itest/resources/features/delete-uk-establishments-link.feature, src/itest/resources/features/uk-establishments.feature, src/itest/resources/json/input/00006405.json, src/itest/resources/json/input/00006406.json, src/itest/resources/json/input/with_links_resource.json, src/itest/resources/json/output/00006406-getUkEstablishments.json, src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java, src/test/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerTest.java, src/test/java/uk/gov/companieshouse/company/profile/service/CompanyProfileServiceTest.java, src/test/java/uk/gov/companieshouse/company/profile/util/TestHelper.java
* Update integration tests to use new json file
* Add new unit and integration tests
Resolves [DSND-1872](https://companieshouse.atlassian.net/browse/DSND-1872)
[DSND-1872]: https://companieshouse.atlassian.net/browse/DSND-1872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-1872: Add delete uk establishments link logic

src/itest/resources/json/input/00006408.json, src/itest/resources/json/output/00006408-getCompanyProfile.json, src/main/java/uk/gov/companieshouse/company/profile/transform/CompanyProfileTransformer.java
* Transformer now generates and persists an etag
* Refactor cucumber tests
Resolves [DSND-2619](https://companieshouse.atlassian.net/browse/DSND-2619)
[DSND-2619]: https://companieshouse.atlassian.net/browse/DSND-2619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2619 Modify CompanyProfileTransformer

routes.yaml
[DSND-2665](https://companieshouse.atlassian.net/browse/DSND-2665)
[DSND-2665]: https://companieshouse.atlassian.net/browse/DSND-2665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2665: Add routes back in for new company profile endpoints

src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java, src/test/java/uk/gov/companieshouse/company/profile/service/CompanyProfileServiceTest.java
* Set date of cessation to value of dissolution date
* Set dissolution date to null if exists
Resolves [DSND-2681](https://companieshouse.atlassian.net/browse/DSND-2681)
[DSND-2681]: https://companieshouse.atlassian.net/browse/DSND-2681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2681: Change logic of retrieve company number

src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java
=> fix checkstyle violations

src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java
- Change the order in which overseas and uk-establishments links are added.
=> change order of uk establishments and overseas links checks

.gitignore, Tiltfile.dev, pom.xml, src/main/java/uk/gov/companieshouse/company/profile/config/ApplicationConfig.java, src/test/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileControllerTest.java
=> SEC-47 CORS

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars, terraform/groups/ecs-service/variables.tf
Increase resources for live, set min and desired counts to 2
=> Update Live Resources

terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
=> Update Live Desired and Max Counts

src/itest/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileE2EITest.java, src/itest/java/uk/gov/companieshouse/company/profile/steps/CompanyProfileSteps.java, src/main/java/uk/gov/companieshouse/company/profile/service/CompanyProfileService.java, src/main/java/uk/gov/companieshouse/company/profile/transform/CompanyProfileTransformer.java, src/test/java/uk/gov/companieshouse/company/profile/controller/CompanyProfileConcurrencyITest.java, src/test/java/uk/gov/companieshouse/company/profile/service/CompanyProfileServiceTest.java
* links versioning implemented
* relevant tests made to improve coverage
* existing tests fixed
[DSND-3006](https://companieshouse.atlassian.net/browse/DSND-3006)
[DSND-3006]: https://companieshouse.atlassian.net/browse/DSND-3006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-3006: Links versioning applied on all links endpoints.

pom.xml, src/itest/java/uk/gov/companieshouse/company/profile/steps/CompanyProfileSteps.java, src/main/java/uk/gov/companieshouse/company/profile/util/DateUtils.java
* Upgrade internal dependency versions
* Upgrade jib maven plugin and spring versions
* Fix failing tests
Resolves [BI-14123](https://companieshouse.atlassian.net/browse/BI-14123)
[BI-14123]: https://companieshouse.atlassian.net/browse/BI-14123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-14123: Set published at format to use 24hr time

terraform/groups/ecs-service/locals.tf
Updates ALB rule priority for links
=> Update ALB rule priorities

terraform/groups/ecs-service/profiles/live-eu-west-2/livesbox/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/stagsbox/vars
Adds profiles for sandbox environments for company-profile-api
Required for authentication journey
=> Add company-profile-api to sandbox envs

pom.xml
https://companieshouse.atlassian.net/browse/LP-1087
* Update library to ensure the new field is recognised and saved to Mongo and returned by GET requests
=> LP-1087 Sync LP 'term' field data from CHIPS to Mongo
